name: Build APK Stable

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Yeh automated docker container saare sahi versions khud andar pack rakhta hai
      - name: Build APK with Locked Buildozer Environment
        uses: ArasPran/buildozer-action@v1
        with:
          buildozer_version: stable

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SmartPump-APK
          path: bin/*.apk
          
