name: Build APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Kivy ka official automated tool jo sab kuch khud sahi version me setup karega
      - name: Build APK using Official Kivy Action
        uses: kivy/buildozer-action@v1
        with:
          workdir: .
          buildozer_version: stable

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SmartPump-APK
          path: bin/*.apk
          
